### ISSUE TITLE
Magic variables have negative NodeID

### ISSUE THREAD

**Issue by moodlezoup** [hrkrshnn/solc-ast-rs#1]
Cool project! Ran into the following issue:

Things like `abi`, `keccak256`, `block`, etc. have negative IDs, but `NodeId` aliases `u64`
https://github.com/ethereum/solidity/blob/develop/libsolidity/analysis/GlobalContext.cpp#L39-L63

**Comment by hrkrshnn** [comment]
Didn't notice that, thank you! Do you want to write a PR for it? @moodlezoup

**Comment by moodlezoup** [comment]
I'm a Rust noob but I gave it a shot 😅
